### PR TITLE
Adding 7th event, refactored to remove duplication

### PR DESCRIPTION
**Pull request by dbernar1**
Hi,

Take a look at what I've done here. It's not perfect but it might be easier to manage the content for events this way.

There will be some small content differences on some event pages, and the appearance is slightly different in some places like the address info under the map.

Let me know what you think and whether you think this would be an OK direction to take this in.

### CODE REVIEW

**Comment by yagudaev** [comment]
It's a step in the right direction, but I don't think json make it easier to manage events.

I think what we need is a markdown filter for the content and then allow you to set a few variables on the template. Something like what `middleman` does (http://middlemanapp.com/basics/templates/). Express already has layouts, so combined with a markdown parser say https://www.npmjs.org/package/markdown a structure that looks something like:

```
views/layouts/event.ejs
views/events/index.ejs // loops through all markdown files grabbing their summary and thumbnail image
views/events/001-event.md
views/events/002-event.md
...
```

That json file will get really long quickly and become unmanageable.

**Comment by dbernar1** [comment]
Thank you very much for the review. I also had pretty much all of the concerns you brought up.

I will make some revisions, and update the pull request.

**Comment by dbernar1** [comment]
Hey. I've done part of the work.

I will take another look tomorrow, but feedback is welcome.

**Comment by dbernar1** [comment]
Good morning,

I've extracted the longer description of the event into md files. Do you know what I could do with the event data that is shared between the event listing and event details page? Where could I put that data?

Also, any thoughts on what I did with locations?

Thanks.

**Comment by yagudaev** [comment]
Good job on getting the markdown to work! That's exactly what I meant.

Went over the commit and left some comments and thoughts as I was reading through it.

To answer your questions, I would move all the stuff from the JSON files into the markdown files. I mentioned `middleman` which is a ruby static site framework. They allow you to enter data inside your views which is used in the layout.

So in a similar fashion after some googling I found this: https://www.npmjs.org/package/meta-marked. It is exactly what I was talking about and will allow us to put metadata relating to each event inside the markdown file.

Then for the `events/index` page you will just need to loop through all the md file and grab the `synopsis` attribute which will be part of the metadata.

**Comment by dbernar1** [comment]
I've moved the event metadata from the json file into the markdown files as you explained - thanks for that. The location data is still in json. Let me know if you have any thoughts around that, or anything else.

I've left the separate commits for now, for easier review. I would like to squash the commits before this is merged in, just let me know when it's ready...

Have a good week!

**Comment by dbernar1** [comment]
Thanks. I've made those two adjustments, opting for the shorter synopsis adjustment for the time being.

**Comment by yagudaev** [comment]
Great job! 99% there :).

About the location data, I see why you kept it there. But we can simply add it to the meta data by adding 2 new properties and renaming 1. 

```
locationLong: 
   - {{first_address_line}}
   - {{second_address_line}}
   - {{third_address_line}}
locationShort: {{nickname}}
locationMap: {{address_to_google_map}} // OPTIONAL
```

The google map iframe and all that just needs to have one basic url. Usually that can be the full address of the place. And by default that should be the case. If however there is some weird description as part of the address, the user can override the default param given to google maps using the `locationMap` attribute.

Finally, I am not sure why you want to squash the commits. Personally I have never used that feature of git and may not fully understand when to use it. But I do like having separate commits. It describes your thought process and can help uncover bugs. I often do check the history of a file when there is a bug there just to see if there is something I am missing.

**Comment by yagudaev** [comment]
Come to think of it. It will make more sense for a location to be something like:

```
location:
  long: 
     - {{first_address_line}}
     - {{second_address_line}}
     - {{third_address_line}}
  short: {{nickname}}
  map: {{address_to_google_map}} // OPTIONAL
```

After we get that committed I will test it and we can merge and deploy the changes.

Thanks for the hard work :).

**Comment by dbernar1** [comment]
I've merged the locations. I don't really like the duplication it creates, but OK.

As far as squashing, it's up to you, I don't mind if you prefer multiple commits.

I feel like this whole pull request deserves just one commit, to keep it contained. I've only recently learned about squashing commits from @swalberg and @amirci, so perhaps you can ask them for more info...

**Comment by pbraun** [comment]
I haven't had time to go over all the changes in detail yet but from what I've seen so far it looks great :-)
Thank you very much. I hope that will make adding new events to the site quicker and less error prone.
:+1:

**Comment by dbernar1** [comment]
Great, you're welcome. My pleasure :)

**Comment by yagudaev** [comment]
Merged everything and deployed to heroku :). Awesome work Dan! Nice and short code no bullshit.

I made just one modification, normally in Node you would never use the sync functions anywhere but scripts. Node only has a single thread of execution and going to disk and waiting means it is blocked for all other incoming requests. 

I first considered just changing the function to use the async versions, but realized we should just preload the resources at startup time and cache them from that point on. I'm glad you did it like that actually, made the refactoring pretty quick and easy. This is way cleaner than using the async versions too. Check it out: https://github.com/yagudaev/winnipegjs/commit/4d14d8492138251375ecc426d64be82b1fd757e8.

The only place I screwed up is spacing. I usually code ruby so by default I have 2 spaces setup for all my code. In this project looks like we have a mixed spaces/tabs code. I should replace it all with 4 spaces, which I think is the defacto for most JS code now. Or has it changed? (been coding in coffee for the last 2 years)

**Comment by pbraun** [comment]
Great job :-) Thank you very much Dan and Mike. I like how much more maintainable the site is becoming.
I also added dynamic event announcement. An announcement on the home page will appear if there is an upcoming event.

**Comment by dbernar1** [comment]
@yagudaev Thank you. Thanks for providing the direction with the event-nnn.md files. There was real synergy in this pull request ;P

Thanks for the pro tip about async vs. sync - I can totally see how sync would be a no-no for a server now. Also good call on the caching.

I like to write CoffeeScript too! I like to write JavaScript too, but CoffeeScript feels a little terser, while still maintaining all the relevant information in the code, IMO.

@pbraun That's great that you added that. I guess I will need to now update the event with the date and RSVP link.

**Pull request merged**
